// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {excel} from '../models';

export function CurrentSheet():Promise<string>;

export function SendRequestPayload(arg1:excel.RequestFormPayload):Promise<void>;

export function Sheets():Promise<Array<string>>;
