// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {excel} from '../models';

export function CreateMaintenanceLog(arg1:repository.CreateMaintenanceLogParams):Promise<repository.MaintenanceLog>;

export function CurrentSheet():Promise<string>;

export function DeleteMaintenanceLog(arg1:number):Promise<void>;

export function GetMaintenanceLogs():Promise<Array<repository.MaintenanceLog>>;

export function GetSerialValue():Promise<number>;

export function SendRequestPayload(arg1:excel.RequestFormPayload):Promise<void>;

export function Sheets():Promise<Array<string>>;
