// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMaintenanceLog(arg1) {
  return window['go']['main']['App']['CreateMaintenanceLog'](arg1);
}

export function CurrentSheet() {
  return window['go']['main']['App']['CurrentSheet']();
}

export function DeleteMaintenanceLog(arg1) {
  return window['go']['main']['App']['DeleteMaintenanceLog'](arg1);
}

export function GetMaintenanceLogs() {
  return window['go']['main']['App']['GetMaintenanceLogs']();
}

export function GetSerialValue() {
  return window['go']['main']['App']['GetSerialValue']();
}

export function SendRequestPayload(arg1) {
  return window['go']['main']['App']['SendRequestPayload'](arg1);
}

export function Sheets() {
  return window['go']['main']['App']['Sheets']();
}
