import { MaintenanceLogFormValues } from "./schema-maintenance";

// This would typically come from your backend
export const maintenanceLogs: (MaintenanceLogFormValues & { id: string })[] = [
  {
    id: "1",
    maintenance_number: "MNT-2024-001",
    date_of_maintenance: new Date("2024-01-15"),
    emitter: "El Brayan",
    fault_description: "Faulty power supply",
    issuing_department: "Electrical",
    used_materials: "Power supply unit, cables",
    maintenance_technician: "El Brayan",
    result: "Replaced power supply",
    observations: "Regular maintenance required",
  },
  {
    id: "2",
    maintenance_number: "MNT-2024-002",
    date_of_maintenance: new Date("2024-02-01"),
    emitter: "Pepe",
    fault_description: "Network connectivity issues",
    issuing_department: "IT",
    used_materials: "Network cable, connector",
    maintenance_technician: "Pepe",
    result: "Fixed network connection",
    observations: "Updated network configuration",
  },
  {
    id: "3",
    maintenance_number: "MNT-2024-002",
    date_of_maintenance: new Date("2024-02-01"),
    emitter: "Mario",
    fault_description: "Network connectivity issues",
    issuing_department: "IT",
    used_materials: "Network cable, connector",
    maintenance_technician: "Mario",
    result: "Fixed network connection",
    observations: "Updated network configuration",
  },
  {
    id: "4",
    maintenance_number: "MNT-2024-002",
    date_of_maintenance: new Date("2024-02-01"),
    emitter: "Jacky Sieras",
    fault_description: "Network connectivity issues",
    issuing_department: "IT",
    used_materials: "Network cable, connector",
    maintenance_technician: "Jacky Sieras",
    result: "Fixed network connection",
    observations: "Updated network configuration",
  },
  {
    id: "5",
    maintenance_number: "MNT-2024-002",
    date_of_maintenance: new Date("2024-02-01"),
    emitter: "Carlitos",
    fault_description: "Network connectivity issues",
    issuing_department: "IT",
    used_materials: "Network cable, connector",
    maintenance_technician: "Bob Johnson",
    result: "Fixed network connection",
    observations: "Updated network configuration",
  },
  {
    id: "6",
    maintenance_number: "MNT-2024-002",
    date_of_maintenance: new Date("2024-02-01"),
    emitter: "Jane Smith",
    fault_description: "Network connectivity issues",
    issuing_department: "IT",
    used_materials: "Network cable, connector",
    maintenance_technician: "Bob Johnson",
    result: "Fixed network connection",
    observations: "Updated network configuration",
  },
];